version: "3.3"

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    depends_on:
      - nexus
      - sonarqube
    environment:
      - DOCKER_HOST=tcp://localhost:2375
      - JENKINS_UC=http://updates.jenkins.io
      - JENKINS_UC_EXPERIMENTAL=http://updates.jenkins.io/experimental
      - JENKINS_INCREMENTALS_REPO_MIRROR=http://repo.jenkins-ci.org/incrementals
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    expose:
      - "8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-home:/home

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    expose:
      - "8081"

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - "./scripts/add-keycloak-db.sh:/docker-entrypoint-initdb.d/add-keycloak-db.sh"

  keycloak:
    image: jboss/keycloak:11.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/karate-quarkus-demo-realm.json"
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_VENDOR: postgres
      DB_ADDR: postgres
    ports:
      - 8180:8080
    volumes:
      - "./scripts/karate-quarkus-demo-realm.json:/tmp/karate-quarkus-demo-realm.json"
    depends_on:
      - postgres

  pub-sub-emulator:
    image: google/cloud-sdk:306.0.0
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085", "--project=df-key-kls-npe-8d1f"]
    ports:
      - "8085:8085"

  nifi:
    image: apache/nifi:1.12.1
    container_name: nifi
    ports:
      - 8080:8080
#    environment:
#      - NIFI_WEB_HTTP_PORT=8080
#    links:
#      - pub-sub-emulator
#    volumes:
#      - ./data:/opt/datafiles
#      - ./config/nifi:/opt/nifi/nifi-current/conf
#      - nifi:/opt/nifi/nifi-current/extensions


volumes:
  nexus-data: {}
  jenkins-data: {}
  jenkins-home: {}
  sonarqube_conf: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  postgresql: {}
  postgresql_data: {}
  nifi: {}
