version: "3.5"
services:

  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - "5080"
      - "6080"
    command: dgraph zero --my=zero1:5080  --idx=1 --logtostderr -v=2 --replicas 1

  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - "8080:8080"
      - "9080:9080"
    command: dgraph alpha --my=alpha1:7080 --zero=zero1:5080 --logtostderr -v=2  --whitelist "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes: {}
