apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
namespace: local
namePrefix: dev-
nameSuffix: -v1

commonLabels:
  environment: local
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am local!

resources:
  - ../../base

configMapGenerator:
#  - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=local
      - LOG_LEVEL=debug

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=local-real-pass

replicas:
  - name: service
    count: 1

images:
  - name: etcd
    newTag: 3.3.15
  - name: postgres
    newTag: 11.5-alpine
  - name: envoyproxy/envoy-alpine
    newName: docker.io/envoyproxy/envoy-alpine
    newTag: v1.14.2
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v2.0.0
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/recorder-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/recorder-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeting-service
    newName: docker.pkg.github.com/xmlking/micro-apps/greeting-service
    newTag: 1.6.1-SNAPSHOT
