[versions]

# kotlin
kotlin = "1.4.32"
#kotlin = "1.5.0-RC"
spek = "2.0.8"
kotest = "4.4.3"
junit = "5.7.1"
serialization = "1.1.0"
avro4k = "0.41.0"
kaml = "0.17.0"
coroutines = "1.4.3"
turbine = "0.4.1"
ktlint = "0.40.0"
mockk = "1.11.0"
arrow = "0.10.5"
konfig = "0.23.0"
mapstruct = "1.4.2.Final"
markdown = "0.1.45"
javafaker = "1.0.2"
# gradle
gradleTool = "7.0"
sonarPlugin = "3.1.1"
spotlessPlugin = "5.12.1"
spotlessClogPlugin = "2.1.2"
dokkaPlugin = "1.4.30"
checkLatestPlugin = "0.38.0"
useLatestPlugin = "0.2.16"
axionPlugin = "1.13.2"
shadowPlugin = "6.1.0"
jibPlugin = "3.0.0"
loggerPlugin = "0.9.0"
protobufPlugin = "0.8.15"
# test matchers
hamcrest = "1.3"
restAssured = "4.3.1"
# Jacoco
jacoco = "0.8.5"
# FIXME change to QualityGate to at lease 0.4
jacocoQualityGate = "0.0"
# logs
kotlinLogging = "2.0.6"
slf4j = "2.0.0-alpha1"
# slf4j = "1.7.30"
# quarkus
quarkusPluginId = "io.quarkus"
quarkusPlugin = "1.13.2.Final"
quarkusPlatform = "1.13.2.Final"
quarkusPlatformGroupId = "io.quarkus"
quarkusPlatformArtifactId = "quarkus-universe-bom"
# to use locally built Quarkus, use `quarkus-bom` and `999-SNAPSHOT`
#quarkusPlatformArtifactId = "quarkus-bom"
#quarkusPlatform = "999-SNAPSHOT"
# grpc
grpc = "1.37.0"
grpcKotlin = "1.0.0"
protobuf = "3.15.8"
pgv = "0.4.1"
guava = "30.1-jre"
sentinel = "1.8.1"
# beam
beam = "2.28.0"
csv = "1.8"
openCsv = "5.0"
uuid = "4.0.1"
# yaml version
yaml = "2.10.3"
# avro version
avro = "1.9.2"
# spring
spring = "2.4.5"
springDependencyManagement = "1.0.11.RELEASE"
# google
googlePubsub = "1.112.1"

[libraries]
guava = { module="com.google.guava:guava", version.ref="guava" }
#junit-jupiter = { module="org.junit.jupiter:junit-jupiter-api", version.ref="jupiter" }
#junit-engine = { module="org.junit.jupiter:junit-jupiter-engine" }
#commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = { strictly = "[3.8,4.0[", prefer = "3.9" } }

[bundles]
#testDependencies = ["junit-jupiter", "junit-engine"]
