resources:
  - "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
    name: proxy_cert
    tls_certificate:
      certificate_chain:
        filename: '/etc/certs/proxy-cert.pem'
      private_key:
        filename: '/etc/certs/proxy-key.pem'
