name: Check

on:
  push:
    branches:
      - develop
      - feature/*
    pull_request:
      branches:
        - '*'
env:
  CI: true

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check code quality
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}
      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: check
        uses: eskatos/gradle-command-action@v1
        id: check
        env:
          CI: true
        with:
          gradle-version: 6.8
          arguments: check
      - name: comment
        uses: unsplash/comment-on-pr@master
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: Build failed ${{ steps.check.outputs.build-scan-url }}
